export const ERROR = 'ERROR';

export const DIR_SET = 'DIR_SET';
export const DIR_CLEAR = 'DIR_CLEAR';

export const PLAYLISTS_LOAD = 'PLAYLISTS_LOAD';
export const PLAYLISTS_SAMPLE = 'PLAYLISTS_SAMPLE';
export const PLAYLISTS_VISITED = 'PLAYLISTS_VISITED';
export const PLAYLISTS_UPDATE = 'PLAYLISTS_UPDATE';
export const PLAYLISTS_CLEAR = 'PLAYLISTS_CLEAR';

export const PLAY_SET = 'PLAY_SET';
export const PLAY_SET_PLAYING = 'PLAY_SET_PLAYING';
export const PLAY_SET_VOLUME = 'PLAY_SET_VOLUME';
export const PLAY_SET_STATE = 'PLAY_SET_STATE';
export const PLAY_TOGGLE_STATE = 'PLAY_TOGGLE_STATE';
export const PLAY_GOTO_PREV = 'PLAY_GOTO_PREV';
export const PLAY_GOTO_NEXT = 'PLAY_GOTO_NEXT';
export const PLAY_CLEAR = 'PLAY_CLEAR';
